env:
  global:
    - secure: oHPNEKMg5lummL2kOIKhsXa8MJAc6+QllClhY2QHX58yqoOTO/VSFEdBn5dyM9K/5n7oT5u27Su/Ov1AWlI/kMI3MqoXIXPa+0EPSdi6Zy4Q1RDd7euH4XJpj+mmlBjaANHRR6fXgJaGv5U+eELGj9+UmHlhAMSxA1S0Wdwt0FFf+TrnXJ0ukwkOzF/mIRM6iAbVuuYblVwM0qAacxCTIuumUy6z1VM5cI5UAmSO7OeFgc+PJGXbrJX6tD9zykSgKyY4X9SLIJWp14I//+r3uSOVXdtuRoerO+p0W8bHE922SNKIcZ0L4Aovmb/sd5a77JpKlB7YaBmVimhBIRC/e+DX0kBgQgYls6bWfr2xeQ2XQa2XftpnS7BTRn00KSRuaa/JW3OSVL2Rm6GIaGdufpW2M8r/4fxulxivzSYWuwdEICh2t7s4JRR3a46Lkt0RkFxssKLRGHuyrhwly+Znakm6ht0uxOE/fwwZsLQGpg3kwoq7dtwZH9oORSjg9XZIYzbXZ6pWTb93IgW993Y/8VjK1knfmD+8OABcz29+lDKbks6cymjchSfhx8jqlPY1oI4E9CZ02ZuyFSrHXBeYwpZcGz9gQdFWBnLJ30ITfQATmswxCJmTmqmbe9jHELLKX5PjJZ4Z6/HiSA4u1ZYlNmXC5YQhBrAFhr++TFPsqCk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/justdomains_mirror1.malwaredomains.com
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
