env:
  global:
    - secure: poYMs1SAGGcIwarmRODeYJWbJJpcWxXJsr//X4z+cRCjbNUs9tdxJdvuaz0KKh55PkXisQJnajG1IvtRdWfdJ4d2wevpyRVR8NCTMHZseCqeLDOWYAHIlHl6BSJRpgfjGBdvtlgcDKto7y2HS1n8p9V4N9mtHibe3+Tp1FErhgInI0xdb6Hf3L4n3TysoiHzXpE8VNoF+JOk5ct7uXt2bzcY2tuJjUssRMLwVN2ZtAfSV3l50+8voWSF4fC/Pta4JqP0kUu3+0VXj7y/4UDEQImbvJsJqbOcCfXvrsFFdObVVEAEUrKOGZrv3IXnfHFuQTN0UU7Z1OKNsZnLjMm/LXm+yChqJ01gva26dQMEShnQkpIrJuGeuV3+w8WVNct84r/9a6e9u9/VPwXRTcNUHzU0GkU2A2XWLglKEP99yPITx1hBRz18MuLsHLDK4m0TmSO5UhAbx21c/qEktgHrnBy/3IiOWTAJ+qtIWCwS+R1POj2K5v5gKU63+BP+gHrrwhqwtjslWEXA1oMNApvpi2tpKE2phXPrSfo+cfKppnuU+lvAZrO41ifUlIZJs+YSnwR9LsZ0JnFb54rCFDi8z8uLslr97kA5xqUtE/Sh/XUTq8mlUlKR91oksGMgovD4JXyc+hDDMEJpKoidX85NdrCRNicfiNrIbv+n7vtQDz0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/justdomains_mirror1.malwaredomains.com
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
