env:
  global:
    - secure: KqeOQdh+nb5re00rpxtmDnMzJO9NOl2trifYZKtp6HW/URxAtr2beGeTftLMlhC4g9as1Bogp6o+dV2Gsl2HicXauCLDIkJ/QaM0OslY62ol1n3IxvPS8oFKVUdt4awiPiJioDKApFQ5lHDY3By3vGNglPPDp05CChPeqUc8OeafjvzKe60PECKWClPMvExtXZ8crxpZHei9BdgAjp9wdREP7+9aIukGKeJeb2t+LeZb3dTxrb/24qFlcUJYAmqnYqmpEqbao7DxoiuI9vC7icCCy321FOxYOyWnI5Qth9NlSGAQEKOobHQigcQy/KRW90pBj0PWL0wb4XkV0dw2DA/aAefMC3BdOlCTC/mCctMHVw8zvxtycXpieZPP+GAfX6WAowaK6EqMZ7Lqlg8uiF2gcJcf93yZp5Y5ywn75QOr+Zq6OSlBOUF6BxgLr2mpgYjIVkygTCx0tV6qzeFNCS+KyKKpV1jbsIF9zf/RVqidOhTY7qYM09SSWusw7lWKk6jf2dKd3ZPzV8PnCTVcU0LpNQvlJ0ZYZ9yLPGvYYDccw0/y9eqDxpkZ0UU95BwT3Xy5XCdSOd8D2i8yNcqIewIRZFR+BEdPv22voU4Kj7GN/aQU4wff55qlyhYeVfKERyEXDND4YcNuQRN8juknN7kcNArQPBHN2Iww67A5nNE=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/justdomains_mirror1.malwaredomains.com
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
