env:
  global:
    - secure: BReA/YWmtWyWm26Av5mDT6YMcfG20TNH4/z9Jxk3TadKiYTpX6XgtGxcJqvI2D+oFUzM88PeyTj+mrlu7L3iosa/snZPD+CuSISHY/Y47Sj0xljSv77x89we8HprWT/IEWwuluP+WZmb8vkJSMauQ+oJjMF5gnfy2QYq+Emf4MHNltmRnRpqGH2KC9cU1xik5oB9KfaKgxmmSKnyg2ksp3JDnAlcpkL86pS+XF/5r62VOqI6ZeVtpGHKKxFa37ZvjGp5DfKP4qFLI3vRGr8px5MaDWQ7MLWUmo+db/rrTIR2yN4qk1Q70ZV6WxBUYVBckuCwBmYdY/VACfhkmgRhJw71QZig9RByejKViJBWd9nMg8cjQqhWf7Bba4bvXMTloCXJBJnmpPnO0/axjxUAQ9oplNglrdBd5qfYA9l01ncec/iBN6nOBCxCD+jpFMarL0jmYyRKXhunnTklxI12K9cn6MedFcDqLkIDsgTnuf3PpcBpGL5nY9kCYhHYsL4w0JScDrmrXv8YtUyMAOp+00EHA6FY/GxKaXAFw6gLyLc6NcxL9h3Mk8Cs+Yf1FNlJTJXU7nlWCkAbO3O1ms+zvE6d/oJZIpOvr4SLW9Atfd20fEqic9LsZ2YmtxhaZbXXvwjNMM6Br+zPxALJTsYT90OtzRZspoHolwSuob/kbTk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/justdomains_mirror1.malwaredomains.com
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
