env:
  global:
    - secure: f5aGGGf2yKuCvIGC5D9oKq3GYvwGy2mOYgwmG+w0/F2o8MbQ8Gagy5SEslEf1AQ5p4+WMJGCZ1wTAxw/LMxrNDApLEG84M8PPbV8tKMwfwfObvXV5NA86BIBfqbQ+gEPNnYN1QplBuWe8WBWzOiYl2HXkAGKyjAugjFk31J+y2m5hmfBzdILxbjrwhL+9QCsSeG+UFH7mx0O4INSKEJ7M/SCN7EHs3eDvfrwrFMmBW6DADIxk/BSUb0aCM4PRCmLyQrs4mCrCJxQcb1p9ZS7Dbpeb7uE3U+vrXcc29ddKYiQ+0FHPxIkyCjGROagKXR94gl+5sVHd/re5hBzuV2POyqtDTN4h1aP2Xyg21pPQRNocxZh8MxrAVzUdrZ9qiS0xIOipliOsQwcbB1WHMbmykWbKo14WBGtEw0hglzy88sqWw9ZB0NUI62EqVG8RVLoZEMLqm5I9Zkp+LkhGVNcOn0HZU6x4nwVZfMbU1FGYKIXvY+aswRXYa8N4BXhOi3xtclf+drzyP/up5nZ0SdrHKySz4hLaBSBVO2SlGfagxHcN13pVELDTnCxXljF5dRFfkuAkhbVq8n23aDyex2LXG1Np+quZqphHESrR+AsDTv3yd9kc2NcsH9eWk1fAp74+WVid3TOne1IPJBVEg/fEAICQjH4GhmJet04PYDJ80Q=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/justdomains_mirror1.malwaredomains.com
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
