env:
  global:
    - secure: rJU4phUpA9W0sFujoJU7L1DkoqYPOgclzdNgdn5/aJrblDYL73kjAge7EqKiJStVNX5CfGX4/8u/j+7EyK6mMpp9HFkpyRKoZK4GEgRuJWGxFKlIVymXA7Qzl2P94Qv84e/uMF9NGrklFYAwdr6iqgvpmhSFmYMVqhsUNNAn6pSofAChivpMBYTXqMe363/Ws3kAxjqhqIan81onxguTyJS7aHzUXokni5+zae5KrwnwA3awKJmOyzakMjYY89b5qVrF0uCjpAChdQbRacRcCNBCqwZz7Odq0ODWmmqD6IjxzTDCnNrcbnsHYloQws2WhQtzX2BhQXBm9JeV3/gY3dM3jIoGQnau4HgqlG0fxy1RNqxd0WNVhldb0Vbqu7/Kog2tUCK3zFkzUIcBR/uRilYx/UqnqdK8OwNmgq8pTtla1gj+UDBt7HSJ0wo/0OxoLjAXe23qd0Qu2w7xNJ4++Ffkd1M3hXg/461sz33AozGPBNko4dzI7DEXmUTSbuB2ysNodCwtZMnEe5ARcmOx2fBWPkagzSFHm9ucsR/kq01mT75NdCJuhh7FMZjr0LLfmUKbFmpmy2FN3Umtn5A+8nF63lrPJGdD9ZRfzLVo7Ze5rAzrrdHDx4sSm1Ag4lXAVYHV0nxi0xfBWBvRoQY1tGXomD/p0cfO8KeylcxV2rs=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/justdomains_mirror1.malwaredomains.com
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
